name: avm

on:
  schedule:
  - cron: '0 2,8,14,20 * * *'

jobs:
  scan:
    runs-on: [windows-latest]
    steps:
    - uses: billziss-gh/avm@v1
      with:
        files: |
            https://github.com/winfsp/winfsp/releases/download/v1.10/winfsp-1.10.22006.msi
            https://github.com/winfsp/winfsp/releases/download/v1.11/winfsp-1.11.22176.msi
            https://github.com/winfsp/winfsp/releases/download/v1.12/winfsp-1.12.22301.msi
            https://github.com/winfsp/winfsp/releases/download/v1.12.22339/winfsp-1.12.22339.msi
            https://github.com/winfsp/winfsp/releases/download/v2.0B2/winfsp-2.0.23033.msi
